name: Build and Push Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - main # check your repo, your default branch might be master!

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build test image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test-up -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test-up npm test
      
      - name: Build all services
        run: docker-compose -f docker-compose.yml build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Push images to Docker Hub
        run: docker-compose -f docker-compose.yml push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
